- id: doi:10.1371/journal.pcbi.1007128
  type: paper
  description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  date: 2020-12-4
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      text: Manuscript Source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/
  tags:
    - open science
    - collaboration
  repo: greenelab/meta-review

- id: doi:10.3390/proteomes9020027
- id: doi:10.1161/CIRCULATIONAHA.119.039642
- id: doi:10.1161/CIRCEP.117.005682
- id: doi:10.1161/CIRCULATIONAHA.118.034361
- id: doi:10.1016/j.amjmed.2017.12.009
- id: doi:10.1161/CIRCRESAHA.116.309977
- id: doi:10.1016/j.yjmcc.2016.09.009
- id: doi:10.1016/j.amjcard.2016.01.031
- id: doi:10.1016/j.jacc.2014.10.042
- id: doi:10.1007/s00395-015-0505-6
- id: doi:10.1161/CIRCRESAHA.116.304940
- id: doi:10.1016/j.ijcard.2015.01.075
- id: doi:10.1161/CIRCEP.115.003098
- id: doi:10.1161/CIRCULATIONAHA.113.006641
- id: doi:10.1093/cvr/cvu151
- id: doi:10.1093/cvr/cvu123
- id: doi:10.1161/CIRCEP.114.001973
- id: doi:10.1161/CIRCULATIONAHA.113.006611
- id: doi:10.1371/journal.pone.0083358
- id: doi:10.1016/j.jacc.2013.02.070
- id: doi:10.1371/journal.pone.0058655
- id: doi:10.1093/cvr/cvt133
- id: doi:10.1016/j.hrthm.2012.08.026